[[headers]]
  for = "/data.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[redirects]]
  from = "/data.json"
  to = "/data.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200