[[headers]]
  for = "/data.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/data.json"
  to = "/data.json"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
